### PR TITLE
Return the request body size and SHA1 hash. Resolves #7 and #8.

### LINKED ISSUE #7: Only include 'body' if the request body is text
Right now, if you send binary data via e.g. a POST call, the service fails with a stack trace html page.  Check the request body content-type and only include the body if it's a whitelisted content type (application/json, text/*, etc).

### PR DESCRIPTION
**Pull request by msavy**
Unprintable characters in a chunk are skipped.

Resolves #7 and #8.

### CODE REVIEW

**Comment by msavy** [comment]
I'm rebasing. Hadn't noticed a change had been made on master. I need to install a newer version of ruby as you've changed it. 

Should be a few minutes.

**Comment by msavy** [comment]
Should merge cleanly now.

File: echo_api.rb [hunk 1]
```diff
@@ -31,46 +32,68 @@ def get_headers
 end
 
 def echo_response
-  request.body.rewind
+  body_hasher = Digest::SHA1.new
+  body = ""
+
+  request.body.each do |chunk|
+    # Exclude obviously non-printable character(s).
+    body << chunk if /[\x00-\x1F]/ !~ chunk
```
Comment (msavy) [inline echo_api.rb]: Only area I think is worth debating - if there's some unprintable character in a chunk I just skip it. This will cause the size to be misreported. Do we care? Easy to change, if so.

**Comment by msavy** [comment]
```
{
  "method": "POST",
  "path": "/a/b/c",
  "args": "a=2",
  "body": "foobarbaz",
  "headers": {
    "HTTP_VERSION": "HTTP/1.1",
    "HTTP_HOST": "localhost:3000",
    "HTTP_USER_AGENT": "curl/7.49.1",
    "HTTP_ACCEPT": "application/json"
  },
  "uuid": "1980d9e2-f6b2-4f04-9030-334f017a2b23",
  "bodySha1": "X1UT+IIv2+UUWvM7ZNjZcNz5XG4=",
  "bodyLength": 9
}
```

```
<?xml version="1.0"?>
<echoResponse>
  <method>POST</method>
  <path>/a/b/c</path>
  <uuid>b3242052-97c3-4dd0-97fb-225813c3ab84</uuid>
  <bodySha1>X1UT+IIv2+UUWvM7ZNjZcNz5XG4=</bodySha1>
  <bodyLength>9</bodyLength>
  <body>foobarbaz</body>
  <headers>
    <header>
      <key>VERSION</key>
      <value>HTTP/1.1</value>
    </header>
    <header>
      <key>HOST</key>
      <value>localhost:3000</value>
    </header>
    <header>
      <key>USER_AGENT</key>
      <value>curl/7.49.1</value>
    </header>
    <header>
      <key>ACCEPT</key>
      <value>application/xml</value>
    </header>
  </headers>
  <args>
    <arg>
      <key>a</key>
      <value>2</value>
    </arg>
  </args>
</echoResponse>
```

File: echo_api.rb (hunk 1 above)
Comment (msavy) [inline echo_api.rb]: OK, that seems reasonable.
